### ISSUE TITLE
Menu select not working

### ISSUE THREAD

**Issue by TreyOblad** [BubkisLord/CharmMod#2]
Whenever I turn the mod on as soon as I open the game it just doesn't show the options all it shows is the words HOLLOW KNIGHT. What should I do?

**Comment by BubkisLord** [comment]
> Whenever I turn the mod on as soon as I open the game it just doesn't show the options all it shows is the words HOLLOW KNIGHT. What should I do?

You should run the mod without the ItemChanger mod...
read the updated readme:


CharmMod - A mod that adds over 20 new charms!
Currently, you cannot pick up charms via randomizer,
but you can gain them when you get the requirements through randomizer.
eg. you get shadow dash from a rancid egg. Now u also have Powerful Dash

THIS MOD IS NOT COMPATIBLE WITH SOME MODS LIKE ITEMCHANGER OR TRANSCENDANCE. (maybe benchwarp and others too. experiment, idk what exactly)
YOU WILL KNOW IT IS NOT COMPATIBLE IF YOUR TITLE SCREEN IS JUST A TITLE AND HAS NO BUTTONS.
IK THIS IS A PROBLEM. AND I AM TRYING TO FIGURE OUT WHAT'S WRONG.
(but is compatible with More Healing mod (adds more healing charms.))


   -- WHAT THE CHARMS DO --

==== WARNING - SPOILERS ====
Quickfall -> Fall faster
Slowfall -> Fall slower
Ravenous Soul -> Get heaps of soul per hit, but take double dmg
Powerful Dash -> Makes your dash faster and go further. Use with dashmaster and sharp shadow. (by itself, sharp shadow makes it go further than dashmaster does by itself.)
Sturdy Nail -> *Doubles* nail damage
Hunter's Mark -> Unlocks ALL journal entries and info
Hungry Soul -> Get lots of soul per hit
Slow Soul -> Get +4 to max health, but go really slow. use with speedtime, speed soul or other charm like that
Enraged Crystal Dash -> Makes crystal dash do 50 damage and go x6 speed
Hollow Knight's Blessing -> makes lifeblood charms better. (including joni's blessing)
Healthy Shell -> gives you 1 mask periodically (but takes 11 soul to balance). if ur at full health, gives u soul.
Glass Cannon -> You die in 1 hit, but one-shot everything. (nail damage is set to 6000)
Wealthy Amulet -> gives 10 geo per hit, but costs 100 geo to heal. can be used with sly deal
Opportunistic Defeat -> Get geo and soul when hit.
Spell Soul -> Makes spells BIG. (can be used with )
Slowtime -> Slows down time. (self explanatory)
Speedtime -> Speeds up time. (self explanatory)
Soul Switch -> Takes health periodically, and gives u soul back. (for spell based builds)
Geo Switch -> Takes health periodically, and gives u geo back. (ur gonna have a lot of geo if u pair this with healthy shell)
Speed Soul -> You move at x3 speed when equipped, but u lose 1 charge of soul periodically. (pair with soul switch and healthy shell for interesting results...)








   -- HOW TO GET CHARMS --

==== WARNING - SPOILERS ====








Quickfall -> Complete Bronze Colosseum
Slowfall -> Complete Silver Colosseum
Ravenous Soul -> Complete Gold Colosseum
Powerful Dash -> Get Shadow Dash
Sturdy Nail -> Get a Nail Art
Hunter's Mark -> Get the Hunter's Mark
Hungry Soul -> Get Dream Gate
Slow Soul -> Get Dream Nail
Enraged Crystal Dash -> Get Crystal Dash and give sly the shopkeeper's key
Hollow Knight's Blessing -> Kill the Hollow Knight (now called Infected Vessel)
Healthy Shell -> Get King's Brand
Glass Cannon -> Kill Pure Vessel (now called Hollow Vessel)
Wealthy Amulet -> Purchase account from banker
Opportunistic Defeat -> Gain the ability to overcharm
Spell Soul -> Kill the Collector
Slowtime -> Get more than 10 grubs
Speedtime -> Get all the grubs
Soul Switch -> Kill the Soul Master
Geo Switch -> Kill the Soul Tyrant
Speed Soul -> Talk to the Nailsmith at Sheo's hut

**Comment by BubkisLord** [comment]
> Whenever I turn the mod on as soon as I open the game it just doesn't show the options all it shows is the words HOLLOW KNIGHT. What should I do?

This problem has now been fixed, I am sure you are aware by now. Just here for other people if they are using an older version of CharmMod/Fyrenest. Just update the version.
